stages:
  - test

e2e_tests:
  image: cirrusci/flutter:latest
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y xvfb x11-utils ffmpeg
    - npm install -g appium
    - npm install
  script:
    - Xvfb :99 -screen 0 1280x720x24 & export DISPLAY=:99
    - appium &
    - export PLATFORM=Android
    - export DEVICE_NAME=emulator-5554
    - export APP_PATH=./app-release.apk
    - npm test
  artifacts:
    paths:
      - mochawesome-report/
      - screenshots/
    expire_in: 1 week
